import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function exportDaylogReport(history) {

  const doc = new jsPDF();

  // ===== Report Title =====
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(23, 49, 38);
  doc.text("DAYLOG PRODUCTIVITY REPORT", 14, 20);

  doc.setDrawColor(49, 84, 66);
  doc.line(14, 24, 195, 24);

  doc.setFontSize(11);
  doc.setTextColor(80);

  doc.text(
    `Generated on: ${new Date().toLocaleString()}`,
    14,
    32
  );


  doc.setFontSize(12);
doc.setTextColor(120);

doc.text(
  "Your Personal Productivity Tracker",
  14,
  38
);

  // ===== Calculate Summary =====

  let totalActivities = 0;
  let totalMinutes = 0;

  const categoryCount = {};

  history.forEach(day => {

    (day.entries || []).forEach(entry => {

      totalActivities++;

      totalMinutes += entry.duration || 0;

      categoryCount[entry.category] =
        (categoryCount[entry.category] || 0) +
        (entry.duration || 0);

    });

  });

  const totalHours = (totalMinutes / 60).toFixed(1);

  let topCategory = "-";
  let highest = 0;

  for (const key in categoryCount) {

    if (categoryCount[key] > highest) {

      highest = categoryCount[key];
      topCategory = key;

    }

  }

  // ===== Summary =====

  doc.setFontSize(16);
  doc.setTextColor(23,49,38);
  doc.text("Summary",14,45);

  doc.setFontSize(12);
  doc.setTextColor(60);

  doc.text(`Days Logged : ${history.length}`,14,55);

  doc.text(`Activities : ${totalActivities}`,14,63);

  doc.text(`Total Hours : ${totalHours} h`,14,71);

  doc.text(`Top Category : ${topCategory}`,14,79);

  // ===== Table =====

  const rows = [];

  history.forEach(day => {

    (day.entries || []).forEach(entry => {

      rows.push([

        day.date,

        entry.activity,

        entry.category,

        entry.start,

        entry.end,

        (entry.duration/60).toFixed(1)+" h"

      ]);

    });

  });

  // ===== Category Summary =====

doc.setFontSize(16);
doc.setTextColor(23,49,38);

doc.text("Category Summary", 110, 45);

let y = 55;

Object.entries(categoryCount).forEach(([category, minutes]) => {

  const hours = minutes / 60;

  const barWidth = Math.min(hours * 4, 60);

  doc.setFontSize(11);
  doc.setTextColor(60);

  doc.text(category, 110, y);

  // Background
  doc.setFillColor(230,230,230);
  doc.rect(145, y-4, 40, 5, "F");

  // Progress
  doc.setFillColor(49,84,66);
  doc.rect(145, y-4, barWidth, 5, "F");

  doc.text(hours.toFixed(1)+" h",188,y);

  y += 10;

});

  autoTable(doc,{

    startY:90,

    head:[[
      "Date",
      "Activity",
      "Category",
      "Start",
      "End",
      "Hours"
    ]],

    body:rows,

    headStyles:{
      fillColor:[23,49,38]
    },

    alternateRowStyles:{
      fillColor:[245,245,245]
    },

    styles:{
      fontSize:10
    }

  });

  // ===== Footer =====

  const pageCount = doc.getNumberOfPages();

  for(let i=1;i<=pageCount;i++){

      doc.setPage(i);

      doc.setFontSize(10);

      doc.setTextColor(120);

      doc.text(

        `Generated by Daylog • Page ${i}/${pageCount}`,

        14,

        290

      );

  }

doc.setFontSize(14);
doc.setTextColor(49,84,66);

doc.text(
  "Keep tracking. Small daily improvements lead to big results!",
  14,
  280
);

  doc.save("Daylog_Report.pdf");

}